### ISSUE TITLE
Volta com a contagem de visualições

### ISSUE THREAD

**Issue by diegoadborges** [AndreLucenaJr/AndreLucenaJr#1]
https://camo.githubusercontent.com/260c8fbec2f52e162afef172d4c2485f53799ce02e39887e3478a273a2d3d97e/68747470733a2f2f6b6f6d617265762e636f6d2f67687076632f3f757365726e616d653d616e6472656c7563656e616a72266c6162656c3d50726f66696c65253230766965777326636f6c6f723d306537356236267374796c653d666c6174

**Comment by AndreLucenaJr** [comment]
Vai se fuder

Em ter., 7 de mai. de 2024 22:04, Diego Borges ***@***.***>
escreveu:

**Comment by AndreLucenaJr** [comment]
Obrigado pelo feedback,espero que você atualize o botzinho também

**Comment by diegoadborges** [comment]
> Obrigado pelo feedback,espero que você atualize o botzinho também

tmj
